#!/bin/bash

# Tell the system the resources you need. Adjust the numbers according to your need, e.g.
# -p batch - use partition/queue named batch
# --time=5:00:00 - set a time limit of 5 hours
#SBATCH -p batch --nodes=1 --gres=gpu:1 --cpus-per-task=4 --time=05:00:00 --mail-type=ALL

#If you use Anaconda, initialize it
. $HOME/anaconda3/etc/profile.d/conda.sh
conda activate myenv

# cd your your desired directory and execute your program, e.g.
cd urban-electricity-load-forecasting
python -u -m train_temporal_fusion > output.log 2>&1
